# Generated by Django 4.2.9 on 2024-01-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDepartMents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('NEWARRIVALS', 'NEWARRIVALS'), ('BESTSELLER', 'BESTSELLER'), ('MOSTPOPULAR', 'MOSTPOPULAR'), ('FEATURED', 'FEATURED')], max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
            ],
        ),
    ]
