# Generated by Django 4.2.9 on 2024-01-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_shipping_customer_user_delete_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
