# Generated by Django 4.2.9 on 2024-01-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
