# Generated by Django 4.2.9 on 2024-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pymentSystem',
            field=models.CharField(default='Cash On Delivery', max_length=100),
        ),
    ]
