# Generated by Django 4.2.9 on 2024-01-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='products',
            name='pdsliderimg1',
            field=models.ImageField(blank=True, null=True, upload_to='Slider Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='pdsliderimg2',
            field=models.ImageField(blank=True, null=True, upload_to='Slider Image'),
        ),
        migrations.AddField(
            model_name='products',
            name='pdsliderimg3',
            field=models.ImageField(blank=True, null=True, upload_to='Slider Image'),
        ),
    ]
