# Generated by Django 4.2.9 on 2024-01-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_test_products_pdsliderimg1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ImageField(default='static/assets/images/brands/category/1.png', upload_to='Brand Image'),
        ),
    ]
