# Generated by Django 4.2.9 on 2024-01-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ImageField(default='brands/category/1.png', upload_to='Brand Image'),
        ),
    ]
