# Generated by Django 5.0.3 on 2024-03-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_products_stock_status_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sort_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='core.subcategory'),
        ),
    ]
