# Generated by Django 5.0.3 on 2024-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contact_contact_question_contactsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
