# Generated by Django 5.0.3 on 2024-04-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_contactsettings_fax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='name',
        ),
    ]
