# Generated by Django 5.0.3 on 2024-04-05 11:52

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sort_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
