# Generated by Django 5.0.3 on 2024-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('in', 'In Stock'), ('out', 'Out of Stock')], default='In Stock', max_length=100, null=True),
        ),
    ]
